/**
 * Domain Types — AprovaMind Decision Engine
 *
 * Pure interfaces and type aliases for the domain layer.
 * No Firestore, no UI, no framework imports.
 *
 * These types describe COMPUTED domain concepts.
 * Persistence types live in `@/types/index.ts`.
 */

import type {
    SubjectHealthStatus,
    SubjectStrategicState,
    AccuracyTrend,
    RecommendationType,
    RecommendationUrgency,
    RecommendationCategory,
    PriorityBand,
    ExamPhase,
} from './enums';

// ═══════════════════════════════════════════════
// INPUT TYPES — what the domain services consume
// ═══════════════════════════════════════════════

/**
 * A study session stripped to domain-relevant fields.
 * Mapped from the persistence `StudySession` at the boundary.
 */
export interface StudySessionInput {
    subject: string;
    durationSeconds: number;
    date: string;          // YYYY-MM-DD
    source: 'timer' | 'manual';
}

/**
 * A question session stripped to domain-relevant fields.
 */
export interface QuestionSessionInput {
    subject: string;
    totalQuestions: number;
    correctAnswers: number;
    date: string;          // YYYY-MM-DD
}

/**
 * A subject within a plan — static configuration.
 */
export interface SubjectPlanInput {
    subject: string;
    /** Relative weight 0–100, sum of all subjects = 100 */
    weight: number;
    /** Manual priority override (1=max). null = let engine decide */
    priorityOverride: number | null;
}

/**
 * A study plan stripped to domain-relevant fields.
 */
export interface PlanInput {
    planId: string;
    name: string;
    subjects: SubjectPlanInput[];
    weeklyGoalHours: number;
    examDate: string | null;  // ISO date or null
    color: string;
    /** User-assigned importance 1 (max) to 5 (min) */
    userPriority: number;
}

// ═══════════════════════════════════════════════
// COMPUTED TYPES — what the domain services produce
// ═══════════════════════════════════════════════

/**
 * Component scores that explain the health status.
 */
export interface SubjectHealthMetrics {
    volumeScore: number;     // 0-150 (clamped 100 for overall)
    frequencyScore: number;  // 0-100
    adherenceScore: number;  // 0-100
    recencyScore: number;    // 0-100
    performanceScore: number | null; // 0-100
    overallScore: number;    // 0-100
}

/**
 * Raw aggregated metrics for a subject.
 */
export interface AggregatedMetrics {
    weeklyActualHours: number;
    weeklyTargetHours: number;
    daysSinceLastStudy: number;
    daysSinceLastQuestion: number | null;
    recentAccuracy: number | null;
    totalHoursAllTime: number;
    totalQuestionsAllTime: number;
    recentQuestionsCount: number;
}

/**
 * Detailed result of a priority score calculation.
 */
export interface PriorityScoreResult {
    score: number;
    band: PriorityBand;
    influencingFactors: {
        weight: number;      // Contribution in percentage points (0-100)
        deviation: number;
        recency: number;
        accuracy: number;
        proximity: number;
    };
    reasons: string[];
}

/**
 * Computed strategic snapshot of a single subject within a plan.
 * Recalculated on every engine cycle — never persisted.
 */
export interface SubjectHealth {
    subject: string;
    planId: string;
    weight: number;

    // ── State ──
    status: SubjectHealthStatus;
    strategicState: SubjectStrategicState;

    // ── Metrics ──
    metrics: SubjectHealthMetrics;
    raw: AggregatedMetrics;

    // ── Priority ──
    priority: PriorityScoreResult;

    /** @deprecated use priority.score */
    priorityScore: number;
    /** @deprecated use priority.band */
    priorityBand: PriorityBand;
}

// ─────────────────────────────────────────────
// Recommendation
// ─────────────────────────────────────────────

/**
 * A concrete, actionable prescription generated by the engine.
 */
export interface Recommendation {
    id: string;
    type: RecommendationType;
    target: string;               // Usually the subject name
    urgency: RecommendationUrgency;
    summary: string;
    reason: string[];             // Structured reasons justifying the recommendation
    suggestedAction: string;      // The concrete action to take
    expectedImpact: string;       // E.g., "Recuperar o desvio de -20%"
    dueWindow: 'today' | 'this_week' | 'next_week' | 'routine';

    // Engine metadata
    priorityScore: number;
    supportData?: {
        currentStatus: SubjectHealthStatus;
        effortPercent: number;
        accuracyPercent: number | null;
        rawDeviation: number;
        daysSinceStudy: number;
    };
    createdAt: string;
}

// ─────────────────────────────────────────────
// Daily Plan
// ─────────────────────────────────────────────

/**
 * A single block within a daily plan.
 */
export interface DailyPlanBlock {
    order: number;
    planId: string;
    planName: string;
    subject: string;
    minutes: number;
    activity: RecommendationCategory;
    reason: string;

    /** IDs of other plans that benefit from this session (credit sharing) */
    sharedWith: string[];
    /** Minutes credited to each shared plan */
    creditedMinutes: Record<string, number>;
}

/**
 * The complete daily action plan output.
 */
export interface DailyPlan {
    date: string;  // YYYY-MM-DD
    totalMinutes: number;
    blocks: DailyPlanBlock[];
    summary: DailyPlanSummary;
}

export interface DailyPlanSummary {
    byPlan: Record<
        string,
        {
            planName: string;
            directMinutes: number;
            creditedMinutes: number;
            effectiveMinutes: number;
        }
    >;
    sharedEfficiencyPercent: number;
}

// ─────────────────────────────────────────────
// Post-Session Feedback
// ─────────────────────────────────────────────

/**
 * Immediate feedback after a study session is saved.
 */
export interface PostSessionFeedback {
    subject: string;
    sessionMinutes: number;
    impact: {
        weeklyProgressBefore: number;
        weeklyProgressAfter: number;
        statusBefore: SubjectHealthStatus;
        statusAfter: SubjectHealthStatus;
        message: string;
    };
    nextRecommendation: {
        subject: string;
        reason: string;
    } | null;
}

// ─────────────────────────────────────────────
// Portfolio (Multi-Edital)
// ─────────────────────────────────────────────

/**
 * Ranking of a single plan within the user's portfolio.
 */
export interface PlanRanking {
    planId: string;
    planName: string;
    color: string;

    riskScore: number;      // 0–100
    urgencyScore: number;   // 0–100
    healthScore: number;    // 0–100 (average of SubjectHealth scores)
    userPriority: number;   // 1–5
    compositeScore: number; // 0–100

    allocatedPercent: number;
    allocatedHours: number;

    phase: ExamPhase;
    daysToExam: number | null;

    subjectHealthSummary: {
        healthy: number;
        mature: number;
        warning: number;
        critical: number;
        neglected: number;
        inefficient: number;
        blind_spot: number;
        no_data: number;
    };
}

/**
 * A subject that appears in multiple plans.
 */
export interface SharedSubject {
    subject: string;
    planIds: string[];
    maxWeight: number;
    avgWeight: number;
    bonusFactor: number;
}

/**
 * Portfolio-level alert.
 */
export interface PortfolioAlert {
    type: 'dispersion' | 'imbalance' | 'plan_at_risk' | 'exam_passed' | 'budget_exceeded';
    severity: 'info' | 'warning' | 'critical';
    message: string;
    relatedPlanIds: string[];
}

/**
 * The complete portfolio view across all plans.
 */
export interface PlanPortfolio {
    userId: string;
    plans: PlanRanking[];
    globalWeeklyBudget: number;
    sharedSubjects: SharedSubject[];
    alerts: PortfolioAlert[];
    kpis: PortfolioKPIs;
    computedAt: string;
}

export interface PortfolioKPIs {
    /** (totalRealHours / globalWeeklyBudget) × 100 */
    budgetAdherencePercent: number;
    /** Higher = more balanced across plans */
    dispersionIndex: number;
    /** % of study time benefiting multiple plans */
    sharingEfficiencyPercent: number;
    /** Count of plans with riskScore > 60 */
    plansAtRisk: number;
}

// ─────────────────────────────────────────────
// Engine Context (aggregated input for services)
// ─────────────────────────────────────────────

/**
 * Everything the Decision Engine needs for a single plan.
 */
export interface PlanEngineContext {
    plan: PlanInput;
    sessions: StudySessionInput[];       // last 30 days
    questions: QuestionSessionInput[];   // last 60 days
    allTimeSessions: StudySessionInput[];
    allTimeQuestions: QuestionSessionInput[];
    today: string; // YYYY-MM-DD
}

/**
 * Everything the Decision Engine needs for cross-plan computation.
 */
export interface PortfolioEngineContext {
    plans: PlanInput[];
    planContexts: Map<string, PlanEngineContext>;
    globalWeeklyBudget: number;
    today: string;
}
